<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DecisionAI.Core/DecisionAI.Core.csproj" />
    <ProjectReference Include="../DecisionAI.Modules/DecisionAI.Modules.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
